# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://manikandan5.github.io/
baseurl: /
title: Manikandan Murugesan
author: Manikandan Murugesan
description: Personal blog and resume
avatar: profile.png
email: manikandan.m@live.co.uk
github: manikandan5 # username
twitter: manikandan_m5
linkedin: murugesanm
stackoverflow: users/7488282/manikandan-murugesan   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
